name: bitcoin_ticker
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"  # Adjusted to support Flutter 3.0 and Dart 2.17 or higher

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5  # Updated to latest version as of current Flutter requirements

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true